name: Frontend ci

on: [pull_request, push]

jobs:
  buildProject:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.2"
      - name: Install dependencies
        run: flutter pub get
      - name: Run lint
        run: flutter analyze 